/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: nigelgoh (https://sketchfab.com/nigelgoh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/viking-room-a49f1b8e4f5c4ecf9e1fe7d81915ad38
title: Viking room
*/

// import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Room(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.Texture1} geometry={nodes.mesh_all1_Texture1_0.geometry} />
        </group>
      </group>
    </group>
  )
}
